### PR TITLE
stream implementation of optional attendees

### PR DESCRIPTION
**Pull request by tonypan2000**
Implementing the optional attendees (including finding the biggest subsets) all in Java streams. Fails almost every test...

### CODE REVIEW

**Comment by tonypan2000** [comment]
It looks like the current algorithm does not try to add the most optional attendees, it settles for accomodating a subset (but not necessarily the largest) of optional attendees.

**Comment by tonypan2000** [comment]
The problem was because the current powerset doesn't include the empty set, when trying to append a stream of an empty String set to a stream of set of set of  string causes some compile errors. 
`Stream.concat(Stream.of(Sets.combinations(attendeeSet, cardinality)), Stream.of(Collections.<String>emptySet()))`

> incompatible types: inference variable R has incompatible bounds equality constraints: java.util.Set<java.lang.String> lower bounds: T,java.util.Set<java.util.Set<E>>,T,java.util.Set<java.lang.String>,T

**Comment by tonypan2000** [comment]
stream solution now fully functional

**Review by jessrenteria — CHANGES_REQUESTED** [review]
Looks like you still need to push the latest version.

**Review by jessrenteria — APPROVED** [review]

**Pull request merged**
